### PR TITLE
fix(PeriphDrivers): Fix UART DMA Transactions and Enable Full Duplex

### LINKED ISSUE #761: UART Leaks DMA Channels, Fails After 8 DMA Transactions
Our Master DMA transaction functions internally acquire a DMA channel, but never release it or expose it to the application code.  After 8 transactions, all DMA channels have been consumed and subsequent transactions will fail to transmit any data.

This is a common design issue we've seen recently in a few other peripherals, and we should apply similar fixes.

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Description

Our UART DMA transactions were essentially unusable, and only happened to work if the transaction function happened to acquire DMA channel 0.

This PR fixes #761 

It implements 2 features:
1. UART DMA "Auto handlers"
2. APIs for using application-defined DMA handlers and channels

### DMA Auto Handlers

**This behavior is disabled by default...** but **I would _like_ to make this the default**.  Please comment.

Users now have the option to enable "auto handlers" for the UART DMA transactions with

```C
MXC_UART_SetAutoDMAHandlers(MXC_UART_GET_UART(...), true);
```

When auto handlers are enabled, the drivers will automatically acquire a DMA channel, enable the IRQ, assign an internal handler function, then release the acquired channel when the transaction's finished.  This makes UART DMA simpler to set up and use.

### New APIs for Assigning DMA Channels

```C
int MXC_UART_SetTXDMAChannel(mxc_uart_regs_t *uart, unsigned int channel);

int MXC_UART_GetTXDMAChannel(mxc_uart_regs_t *uart);

int MXC_UART_SetRXDMAChannel(mxc_uart_regs_t *uart, unsigned int channel);

int MXC_UART_GetRXDMAChannel(mxc_uart_regs_t *uart);
```

New APIs have been added for managing the UART DMA channels manually.  The application code is responsible for acquiring a channel and assigning an appropriate handler.  The application is also responsible for releasing the channel when necessary.

```C
void UART_DMA_Handler(void)
{
    MXC_DMA_Handler();
}

int main()
{
    /* This section shows the setup required for using application-defined 
    UART DMA handlers.  The application code is responsible for acquiring 
    DMA channels, assigning the right IRQ to an ISR, calling the default
    DMA handler, and releasing acquired channels if necessary. */
    error = MXC_DMA_Init(DMA_INSTANCE);
    if (error) {
        printf("Failed to initialize DMA with error %i\n", error);
    }

    int channel = MXC_DMA_AcquireChannel(DMA_INSTANCE);
    if (channel < 0) {
        printf("Failed to acquire DMA Channel with error %i\n", error);
    }

    // Enable the IRQ for the acquired channel,
    // and set the ISR to the application-defined handler.
    IRQn_Type irq = MXC_DMA_CH_GET_IRQ(channel);
    NVIC_EnableIRQ(irq);
    MXC_NVIC_SetVector(irq, UART_DMA_Handler);

    // Tell the UART DMA transaction functions to use the acquired channel.
    MXC_UART_SetTXDMAChannel(MXC_UART_GET_UART(CONSOLE_UART), channel);

    // ...
}
```
 
### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
For readability I've applied these changes for the ME14.  Will port after review.  The Rev B and C UART drivers may also need these fixes.

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 1]
```diff
@@ -617,12 +684,63 @@ unsigned int MXC_UART_RevA_WriteTXFIFO(mxc_uart_reva_regs_t *uart, unsigned char
...
+    return states[n].channelRx;
+}
+
 unsigned int MXC_UART_RevA_WriteTXFIFODMA(mxc_uart_reva_regs_t *uart, mxc_dma_regs_t *dma,
                                           unsigned char *bytes, unsigned int len,
                                           mxc_uart_dma_complete_cb_t callback,
                                           mxc_dma_config_t config)
 {
-    uint8_t channel;
+    uint8_t channel = -1;
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:743]: Assigning -1 to unsigned integer.

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 2]
```diff
@@ -548,6 +560,49 @@ unsigned int MXC_UART_RevA_ReadRXFIFO(mxc_uart_reva_regs_t *uart, unsigned char
...
+        Some complications make this the most attractive short-term
+        option.  We could handle multiple DMA instances better in the DMA API (See the mismatch between the size of "dma_resource" array and the number of channels per instance, to start)*/
+    if (dma_instance == MXC_DMA0) {
+        MXC_NVIC_SetVector(MXC_DMA_CH_GET_IRQ(channel), MXC_UART_RevA_DMA0_Handler);
+    } else if (dma_instance == MXC_DMA1) {
+        MXC_NVIC_SetVector(MXC_DMA_CH_GET_IRQ(channel), MXC_UART_RevA_DMA1_Handler);
+    }
+#else
+    // Only one DMA instance, we can point direct to MXC_DMA_Handler
+    MXC_NVIC_SetVector(MXC_UART_RevA_DMA0_Handler, MXC_DMA_Handler);
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:597]: Shouldn't this be `MXC_NVIC_SetVector(MXC_DMA_GET_CH_IRQ(channel), MXC_DMA_Handler)` ?

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 3]
```diff
@@ -565,11 +620,24 @@ int MXC_UART_RevA_ReadRXFIFODMA(mxc_uart_reva_regs_t *uart, mxc_dma_regs_t *dma,
         return E_NULL_PTR;
     }
 
+    if (states[uart_num].auto_dma_handlers) {
+        /* Acquire channel */
 #if TARGET_NUM == 32665
-    channel = MXC_DMA_AcquireChannel(dma);
+        channel = MXC_DMA_AcquireChannel(dma);
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:626]: Only acquire channel if we don't already have one?

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 4]
```diff
@@ -635,11 +753,22 @@ unsigned int MXC_UART_RevA_WriteTXFIFODMA(mxc_uart_reva_regs_t *uart, mxc_dma_re
         return E_NULL_PTR;
     }
 
+    if (states[uart_num].auto_dma_handlers) {
+        /* Acquire channel */
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:757]: Same here. Do we only want to acquire if we haven't already?

File: Libraries/PeriphDrivers/Include/MAX32665/uart.h [hunk 5]
```diff
@@ -700,6 +700,12 @@ uint32_t MXC_UART_GetAsyncTXCount(mxc_uart_req_t *req);
  */
 uint32_t MXC_UART_GetAsyncRXCount(mxc_uart_req_t *req);
 
+int MXC_UART_SetAutoDMAHandlers(mxc_uart_regs_t *uart, bool enable);
```
[the remark this answers is not in the document]
Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Include/MAX32665/uart.h:720]: https://github.com/Analog-Devices-MSDK/msdk/pull/763/commits/fade8a5ad0158add66bb11f622a2bc0ae0325573

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c (hunk 2 above)
Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/UART/uart_reva.c]: https://github.com/Analog-Devices-MSDK/msdk/pull/763/commits/2cd7d4ffd4a40f7489e81f3c398f9cbe0044256c

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c (hunk 1 above)
Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/UART/uart_reva.c]: https://github.com/Analog-Devices-MSDK/msdk/pull/763/commits/dc04d78fd1b005b7da86f3e75e341b9a0868417a

**Review by EricB-ADI — APPROVED** [review]

File: Libraries/PeriphDrivers/Source/UART/uart_revb.c [hunk 6]
```diff
@@ -1021,35 +1131,38 @@ int MXC_UART_RevB_TransactionDMA(mxc_uart_revb_req_t *req)
     MXC_UART_DisableInt((mxc_uart_regs_t *)(req->uart), 0xFFFFFFFF);
     MXC_UART_ClearFlags((mxc_uart_regs_t *)(req->uart), 0xFFFFFFFF);
 
-    MXC_UART_ClearTXFIFO((mxc_uart_regs_t *)(req->uart));
-    MXC_UART_ClearRXFIFO((mxc_uart_regs_t *)(req->uart));
+    // Clearing the RX FIFOs here makes RX-only or TX-only
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/UART/uart_revb.c:1134]: Did you mean to leave this commented out? TBH we should probably talk about whether or not we want to clear FIFOs in the other transaction functions as well. That may be outside the scope of this PR though.

**Review by Jacob-Scheiffler — COMMENTED** [review]
Looks good overall. Just a couple of minor comments to discuss before I can bestow you with a green checkmark.

**Review by EricB-ADI — APPROVED** [review]

**Comment by Jake-Carter** [comment]
Thanks @lorne-maxim, updated in https://github.com/Analog-Devices-MSDK/msdk/pull/763/commits/831c893012b439cbbb9cc00915c129b3b1d59a79

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 7]
```diff
@@ -617,12 +685,62 @@ unsigned int MXC_UART_RevA_WriteTXFIFO(mxc_uart_reva_regs_t *uart, unsigned char
...
+
+    states[n].auto_dma_handlers = enable;
+
+    return E_NO_ERROR;
+}
+
+int MXC_UART_RevA_SetTXDMAChannel(mxc_uart_reva_regs_t *uart, unsigned int channel)
+{
+    int n = MXC_UART_GET_IDX((mxc_uart_regs_t *)uart);
+    if (n < 0)
```
Comment (lorne-maxim) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:701]: Here is another place where ASSERT may be better.  I see other places (not just in the code this PR touches) that could be ASSERTs also.  IMO, anything that checks to see if a valid UART instance was passed in is better as an ASSERT.

**Review by lorne-maxim — APPROVED** [review]

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c (hunk 7 above)
Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/UART/uart_reva.c:677]: https://github.com/Analog-Devices-MSDK/msdk/pull/763/commits/34db845346d0cd3b2dc574ea0b2dffcc4570d175

Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/UART/uart_reva.c]: @lorne-maxim I ended up purging the asserts except for once in the Init functions.  The compiler should catch those cases as type-cast mismatch, so I think the checks for a valid UART instance in every function were overkill anyways...

It reduces our kid size pretty significantly, which is nice

**Comment by Jake-Carter** [comment]
Added API change tag for non-breaking additions of new functions

File: Libraries/PeriphDrivers/Source/UART/uart_reva.c [hunk 8]
```diff
@@ -601,7 +620,6 @@ int MXC_UART_RevA_ReadRXFIFODMA(mxc_uart_reva_regs_t *uart, mxc_dma_regs_t *dma,
     srcdst.dest = bytes;
     srcdst.len = len;
 
-    states[uart_num].channelRx = channel;
     MXC_DMA_ConfigChannel(config, srcdst);
     MXC_DMA_SetCallback(channel, MXC_UART_DMACallback);
```
Comment (aniktash) [inline Libraries/PeriphDrivers/Source/UART/uart_reva.c:624]: should it not be callback instead of MXCUART_DMACallback ?

Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/UART/uart_reva.c:624]: @aniktash In this case we want to assign the callback to the driver's internal one, because it will check to ensure that both the RX and TX components of the transaction are completed before calling the user's callback.

`MXC_UART_DMACallback` eventually gets routed to `MXC_UART_RevA_DMACallback` - see [here](https://github.com/analogdevicesinc/msdk/blob/6cb136f68ca6c4fdac650a7d59d97550222bf29d/Libraries/PeriphDrivers/Source/UART/uart_reva.c#L1024)
