### PR TITLE
MXC_SYS:  Add Support for External Clock Inputs, Fix MXC_SYS API Documentation

### LINKED ISSUE #518: MXC_SYS Missing EXT_CLK Support
Hi, is there a bug in the MXC_SYS implementation for the MAX32670?

In the [UG](https://www.analog.com/media/en/technical-documentation/user-guides/max32670max32671-user-guide.pdf), the clock tree (page 38) and GCR_CLKCTRL register description (page 66-67) both document an external clock as an available system clock option.
However, the implementation in sys_me15.c has support for EXTCLK removed:

In MXC_SYS_ClockSourceEnable (returns an error)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // MXC_GCR->clkctrl |= MXC_F_GCR_CLKCTRL_EXTCLK_EN;
        // return MXC_SYS_Clock_Timeout(MXC_F_GCR_CLKCTRL_EXTCLK_RDY);
        return E_NOT_SUPPORTED;
        break;
```

In MXC_SYS_ClockSourceDisable (silent failure)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // MXC_GCR->clkctrl &= ~MXC_F_GCR_CLKCTRL_EXTCLK_EN;
        break;
```

In MXC_SYS_ClockSelect (silent failure)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // Enable HIRC clock
        // if(!(MXC_GCR->clkctrl & MXC_F_GCR_CLKCTRL_EXTCLK_EN)) {
        //     MXC_GCR->clkctrl |=MXC_F_GCR_CLKCTRL_EXTCLK_EN;

        //     // Check if HIRC clock is ready
        //     if (MXC_SYS_Clock_Timeout(MXC_F_GCR_CLKCTRL_EXTCLK_RDY) != E_NO_ERROR) {
        //         return E_TIME_OUT;
        //     }
        // }

        // Set HIRC clock as System Clock
        // MXC_SETFIELD(MXC_GCR->clkctrl, MXC_F_GCR_CLKCTRL_SYSCLK_SEL, MXC_S_GCR_CLKCTRL_SYSCLK_SEL_EXTCLK);

        break;
```

I will be populating the EXT_CLK footprint on my EV kit to test this disabled code.

(Also, MXC_SYS does not appear in the [peripheral documentation](https://analog-devices-msdk.github.io/msdk/Libraries/PeriphDrivers/Documentation/MAX32670/modules.html).)

### PR DESCRIPTION
**Pull request by Jake-Carter**
Resolves #518 

## Overvew

- Enable the external clock input as an option for the system clock source for microcontrollers that support it (mxc_sys).
- Add the `EXT_CLK` example for the MAX32670.
- Update Doxygen files to include static members.  This fixes missing documentation for some mxc_sys functions (`MXC_SYS_Crit_xxx`) and macro (`MXC_CRITICAL(xxx)`).
- Fix missing mxc_sys section in API doxygen for all micros.
- Improve mxc_sys API documentation (see [here ](https://jake-carter.github.io/msdk/Libraries/PeriphDrivers/Documentation/MAX32670/group__mxc__sys.html) for example)

## Testing

- Tested with the MAX32670EVKIT (Rev B) with a 2Mhz 50% duty cycle square wave provided from a function generator.  At higher clock frequencies (i.e. 20Mhz) operation became unreliable due to ringing/impedance mismatch causing degradation of the clock signal.  This was a limitation of the test setup.  Given a clean signal, the microcontroller is expected to function up to the specs of its datasheet.

### CODE REVIEW

File: Libraries/PeriphDrivers/Source/SYS/sys_ai85.c [hunk 1]
```diff
@@ -377,18 +383,13 @@ int MXC_SYS_Clock_Select(mxc_sys_system_clock_t clock)
...
-        //     if (MXC_SYS_Clock_Timeout(MXC_F_GCR_CLKCTRL_EXTCLK_RDY) != E_NO_ERROR) {
-        //         return E_TIME_OUT;
-        //     }
-        // }
-
-        // Set HIRC clock as System Clock
-        // MXC_SETFIELD(MXC_GCR->clkctrl, MXC_F_GCR_CLKCTRL_SYSCLK_SEL, MXC_S_GCR_CLKCTRL_SYSCLK_SEL_EXTCLK);
+        // No EXT_CLK "RDY" bit for AI85 so we enable every time
+        err = MXC_SYS_ClockSourceEnable(MXC_SYS_CLOCK_EXTCLK);
+        if (err)
```
Comment (Jacob-Scheiffler) [inline Libraries/PeriphDrivers/Source/SYS/sys_ai85.c:388]: Add brackets.

**Review by Jacob-Scheiffler — CHANGES_REQUESTED** [review]
Did we get a customer request for the example? If so, consider adding it for other micros which support external clocks as well.

File: Libraries/PeriphDrivers/Source/SYS/sys_ai85.c (hunk 1 above)
Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/SYS/sys_ai85.c:388]: > Did we get a customer request for the example? If so, consider adding it for other micros which support external clocks as well.

I haven't added the example universally yet because of the testing overhead associated with it.  We've got the internal SGS group looking at this specifically for the ME15, but I don't think I'll have time to port + test the example universally yet.  Todo in a future PR

Comment (Jake-Carter) [reply Libraries/PeriphDrivers/Source/SYS/sys_ai85.c]: > Add brackets.

-.-

https://github.com/Analog-Devices-MSDK/msdk/pull/521/commits/0240928ae0077cb4651bbe52a4c526f63a71a2d0

**Review by Jacob-Scheiffler — APPROVED** [review]

**Review by sihyung-maxim — APPROVED** [review]
