### PR TITLE
fix(Boards, Examples): Fix MAX32690 GPIO Example 

### LINKED ISSUE #705: No GPIO IRQ handlers defined for MAX32690 EvKit_V1
The provided GPIO example for EvKitV1 does not work as expected, execution stops as soon as the gpio interrupt is triggered.

The GPIO IRQ handlers are declared in  startup_max32690.s:

    def_irq_handler GPIO0_IRQHandler             /* 0x28  0x00A0  40: GPIO0 */
    def_irq_handler GPIO1_IRQHandler             /* 0x29  0x00A4  41: GPIO1 */
    def_irq_handler GPIO2_IRQHandler             /* 0x2A  0x00A8  42: GPIO2 */

However, there is no IRQ handler function that matches these names in board.c for the EvKitV1, so the common handler is never called.

The definition was provided for other evaluation kits:

```
__weak void GPIO2_IRQHandler(void)
{ 
MXC_GPIO_Handler(MXC_GPIO_GET_IDX(MXC_GPIO2)); 
} 
```

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Description

Fixes #705 

This PR defines weak default handlers for the ports used by the pushbutton and GPIO example on the MAX32690 EVKIT.

The MAX32690 GPIO example has also been updated to be less reliant on these weak handlers, and to be less confusing in general.

### Test

GPIO Example now functions on the MAX32690EVKIT (LED1 blinks when PB0 is pressed).

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [x] Description of changes and all other relevant information.
- [x] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

File: Libraries/Boards/MAX32690/EvKit_V1/Source/board.c [hunk 1]
```diff
@@ -101,6 +101,18 @@ __weak void GPIOWAKE_IRQHandler(void)
...
 }
 
+// Default handler for generic GPIO interrupts on port 2 (used by GPIO example)
+__weak void GPIO2_IRQHandler(void)
+{
+    MXC_GPIO_Handler(MXC_GPIO_GET_IDX(MXC_GPIO2));
+}
+
+// Default handler for generic GPIO interrupts on port 4 (used by pushbutton)
+__weak void GPIO4_IRQHandler(void)
```
Comment (Jacob-Scheiffler) [inline Libraries/Boards/MAX32690/EvKit_V1/Source/board.c:111]: I believe GPIOWAKE is the interrupt vector for GPIO4.

Comment (Jake-Carter) [reply Libraries/Boards/MAX32690/EvKit_V1/Source/board.c]: Thanks, removed in https://github.com/Analog-Devices-MSDK/msdk/pull/712/commits/e926cf21f0a52a935583087f438bdf8e0cf3237e

**Review by sihyung-maxim — APPROVED** [review]

**Review by Jacob-Scheiffler — APPROVED** [review]
