### PR TITLE
fix(SDHC): Fix SDHC Driver Clock Divider for MAX78002  

### LINKED ISSUE #797: MAX78002 SDHC Raw example sets SD clock incorrectly.
The SD card clock is tapped directly from the 120MHz internal primary oscillator. There is clock divider with divide by 2 and divide by 4 options. This should always be set to divide by 4 to keep the clock below the 52MHz max for eMMC. In the current code the divider is configured based on the system clock, which is unrelated to the SD clock.

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Description

Closes #797 and implements #791 for the MAX780002 

Ports the MAX78002 SDHC_FAT example using the new CLI for #770 

Also reduces the default SDHC_CLK_FREQ to 30Mhz, since MAX78002 initializes with the 60Mhz ISO by default.

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Review by lorne-maxim — APPROVED** [review]

File: Examples/MAX78002/SDHC_Raw/main.c [hunk 1]
```diff
@@ -296,13 +296,13 @@ int main(void)
...
-        printf("SD clock ratio (at card) 2:1\n");
-        MXC_SDHC_Set_Clock_Config(0);
-    }
+    // if (SystemCoreClock > 96000000) {
+    //     printf("SD clock ratio (at card) 4:1\n");
+    //     MXC_SDHC_Set_Clock_Config(1);
+    // } else {
+    //     printf("SD clock ratio (at card) 2:1\n");
+    //     MXC_SDHC_Set_Clock_Config(0);
+    // }
```
Comment (sihyung-maxim) [inline Examples/MAX78002/SDHC_Raw/main.c:305]: Are we leaving these in just in case?

**Review by sihyung-maxim — APPROVED** [review]

File: Examples/MAX78002/SDHC_Raw/main.c (hunk 1 above)
Comment (Jake-Carter) [reply Examples/MAX78002/SDHC_Raw/main.c:305]: Thanks, good catch.  I was, but they can be removed now
